version: '3.8'

services:
  # Aplikasi PHP-FPM
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ci4_app
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - ci4_network

  # Web Server Nginx
  webserver:
    image: nginx:alpine
    container_name: ci4_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ci4_network

  # Database PostgreSQL
  db:
    image: postgres:17-alpine
    container_name: ci4_db
    restart: always
    environment:
      POSTGRES_DB: db_ci4
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_rahasia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ci4_network

networks:
  ci4_network:
    driver: bridge

volumes:
  pgdata:
