<?php
/**
 * @package 	eProcurement Application
 * @author 		eproc2025
 * @since 		25. Version 3.1
 * 
 */

  include_once('entity.php');

  class DashPermohonanPaketui extends Entity{

	var $query;
  function __construct(){
    parent::__construct();
  }

  function PermohonanPaket()
	{
    $this->Entity();
  } 
  
  function selectByParams($paramsArray=array(),$limit=-1,$from=-1, $statement='',$order="")
	{
		$str = "SELECT A.* FROM (
              SELECT A.ID, A.TAHUN, A.KODE_RUP, A.KODE_SA, A.KODE_DPSJ, A.NO_URUT, A.KATEGORI_PAKET_ID, A.NAMA_PAKET, A.NILAI_PAGU, A.LIST_KEGIATAN, A.WAKTU_AWAL,
              A.WAKTU_AKHIR, A.STATUS_PROSES, A.CREATED_BY, A.CREATED_AT, A.UPDATED_BY, A.UPDATED_AT, A.NAME, A.KATEGORI_PAKET, A.NAMA_SA, A.NAMA_DPSJ,
              A.METODE_PEMILIHAN, A.NAMA_JENIS_PEKERJAAN, A.HASIL_VERIFIKASI, A.IMPORT_DATE, A.IMPORT_FILE, B.PERMOHONAN_PAKET_ID, C.PERMOHONAN_PAKET_ANALISA_ID, A.KODE_PR, B.KODE_PR KODE_PR_PERMOHONAN, A.KODE_PR KODE_PR_RUP, A.NILAI_PAGU_PR
              FROM IMPORT_SIRUP A
              LEFT JOIN PERMOHONAN_PAKET B ON A.ID=B.SIRUP_ID
              LEFT JOIN PERMOHONAN_PAKET_ANALISA C ON B.PERMOHONAN_PAKET_ANALISA_ID=C.PERMOHONAN_PAKET_ANALISA_ID
					  ) A WHERE 1=1 ";

		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		$str .= $statement." ".$order;
		$this->query = $str;
		return $this->selectLimit($str,$limit,$from);
  }

  function sumPaguByParams($paramsArray=array(),$limit=-1,$from=-1, $statement='',$order="")
	{
		$str = "SELECT SUM(A.NILAI_PAGU) TOTAL_PAGU, SUM ( A.NILAI_PAGU_PR ) TOTAL_RAB FROM (
              SELECT A.ID, A.TAHUN, A.KODE_RUP, A.KODE_SA, A.KODE_DPSJ, A.NO_URUT, A.KATEGORI_PAKET_ID, A.NAMA_PAKET, A.NILAI_PAGU, A.LIST_KEGIATAN, A.WAKTU_AWAL, A.WAKTU_AKHIR, A.STATUS_PROSES, A.CREATED_BY, A.CREATED_AT, A.UPDATED_BY, A.UPDATED_AT, A.NAME, A.KATEGORI_PAKET, A.NAMA_SA, A.NAMA_DPSJ,A.METODE_PEMILIHAN, A.NAMA_JENIS_PEKERJAAN, A.HASIL_VERIFIKASI, A.IMPORT_DATE, A.IMPORT_FILE, B.PERMOHONAN_PAKET_ID, C.PERMOHONAN_PAKET_ANALISA_ID, A.KODE_PR, B.KODE_PR KODE_PR_PERMOHONAN, A.KODE_PR KODE_PR_RUP, A.NILAI_PAGU_PR
              FROM IMPORT_SIRUP A
              LEFT JOIN PERMOHONAN_PAKET B ON A.ID=B.SIRUP_ID
              LEFT JOIN PERMOHONAN_PAKET_ANALISA C ON B.PERMOHONAN_PAKET_ANALISA_ID=C.PERMOHONAN_PAKET_ANALISA_ID
							) A WHERE 1=1 ";

								while(list($key,$val) = each($paramsArray))
								{
									$str .= " AND $key = '$val' ";
								}

					$str .= $statement." ".$order;
		$str .= '';
		// echo $str; die();
		$this->query = $str;


		return $this->selectLimit($str,$limit,$from);
  }

  function selectByParamsPersiapan($paramsArray=array(),$limit=-1,$from=-1, $statement='',$order="")
	{
		$str = "SELECT A.* FROM (
              SELECT A.PERMOHONAN_PAKET_ID, A.USER_LOGIN_ID, A.UNIT_KERJA_ID, A.NAMA, A.LAST_CREATE_USER, A.LAST_CREATE_DATE, A.NILAI, A.APPROVAL APPROVAL_PERMOHONAN_PAKET,
              A.PERMOHONAN_PAKET_ANALISA_ID, A.TAHUN_ANGGARAN, A.JENIS_BARANG_JASA, D.NAMA JENIS_BARANG_JASA_NAMA, A.PERKIRAAN_BIAYA_HARGA, A.WAKTU_PENGGUNA_BARANGJASA,
              A.RENCANA_PENGADAAN, A.CREATED_BY, A.CREATED_DATE, A.KODE_RUP, A.KODE_PR, A.SIRUP_ID, A.STRATEGI_PENGADAAN, B.KODE_SA, B.KODE_DPSJ, B.NO_URUT, B.KATEGORI_PAKET_ID, B.LIST_KEGIATAN,B.STATUS_PROSES, B.CREATED_BY CREATED_BY_USER,  B.CREATED_AT, B.UPDATED_BY, B.UPDATED_AT, B.NAME, B.KATEGORI_PAKET, B.NAMA_SA, B.NAMA_DPSJ,
              B.METODE_PEMILIHAN, C.APPROVAL APPROVAL_PERMOHONAN_PAKET_ANALISA, E.KETERANGAN APPROVAL_PERMOHONAN_PAKET_ANALISA_TEXT, C.PUBLISH, (SELECT COUNT(AA.PERMOHONAN_PAKET_ID) TOTAL FROM PERMOHONAN_PAKET_APPROVAL AA WHERE AA.PERMOHONAN_PAKET_ID=A.PERMOHONAN_PAKET_ID) TOTAL_APPROVED, A.NILAI_RAB_PR, A.NILAI_HPS_PR
              FROM PERMOHONAN_PAKET A
              JOIN IMPORT_SIRUP B ON B.ID=A.SIRUP_ID
              JOIN PERMOHONAN_PAKET_ANALISA C on A.PERMOHONAN_PAKET_ANALISA_ID=C.PERMOHONAN_PAKET_ANALISA_ID
              JOIN PAKET_JENIS D on A.JENIS_BARANG_JASA=D.PAKET_JENIS_ID
              JOIN PERMOHONAN_PAKET_ANALISA_MATRIX E ON C.APPROVAL=E.PERMOHONAN_PAKET_ANALISA_MATRIX_ID
            ) A
				WHERE 1 = 1";

								while(list($key,$val) = each($paramsArray))
								{
									$str .= " AND $key = '$val' ";
								}

					$str .= $statement." ".$order;
		$str .= '';
		// echo $str; die();
		$this->query = $str;


		return $this->selectLimit($str,$limit,$from);
  }

  function sumHpsByParams($paramsArray=array(),$limit=-1,$from=-1, $statement='',$order="")
	{
		$str = "SELECT SUM(A.NILAI_HPS_PR) NILAI_HPS_PR FROM (
              SELECT A.* FROM (
		              SELECT A.PERMOHONAN_PAKET_ID, A.USER_LOGIN_ID, A.UNIT_KERJA_ID, A.NAMA, A.LAST_CREATE_USER, A.LAST_CREATE_DATE, A.NILAI, A.APPROVAL APPROVAL_PERMOHONAN_PAKET,
		              A.PERMOHONAN_PAKET_ANALISA_ID, A.TAHUN_ANGGARAN, A.JENIS_BARANG_JASA, D.NAMA JENIS_BARANG_JASA_NAMA, A.PERKIRAAN_BIAYA_HARGA, A.WAKTU_PENGGUNA_BARANGJASA,
		              A.RENCANA_PENGADAAN, A.CREATED_BY, A.CREATED_DATE, A.KODE_RUP, A.KODE_PR, A.SIRUP_ID, A.STRATEGI_PENGADAAN, B.KODE_SA, B.KODE_DPSJ, B.NO_URUT, B.KATEGORI_PAKET_ID, B.LIST_KEGIATAN,B.STATUS_PROSES, B.CREATED_BY CREATED_BY_USER,  B.CREATED_AT, B.UPDATED_BY, B.UPDATED_AT, B.NAME, B.KATEGORI_PAKET, B.NAMA_SA, B.NAMA_DPSJ,
		              B.METODE_PEMILIHAN, C.APPROVAL APPROVAL_PERMOHONAN_PAKET_ANALISA, E.KETERANGAN APPROVAL_PERMOHONAN_PAKET_ANALISA_TEXT, C.PUBLISH, (SELECT COUNT(AA.PERMOHONAN_PAKET_ID) TOTAL FROM PERMOHONAN_PAKET_APPROVAL AA WHERE AA.PERMOHONAN_PAKET_ID=A.PERMOHONAN_PAKET_ID) TOTAL_APPROVED, A.NILAI_RAB_PR, A.NILAI_HPS_PR
		              FROM PERMOHONAN_PAKET A
		              JOIN IMPORT_SIRUP B ON B.ID=A.SIRUP_ID
		              JOIN PERMOHONAN_PAKET_ANALISA C on A.PERMOHONAN_PAKET_ANALISA_ID=C.PERMOHONAN_PAKET_ANALISA_ID
		              JOIN PAKET_JENIS D on A.JENIS_BARANG_JASA=D.PAKET_JENIS_ID
		              JOIN PERMOHONAN_PAKET_ANALISA_MATRIX E ON C.APPROVAL=E.PERMOHONAN_PAKET_ANALISA_MATRIX_ID
		            ) A
							) A WHERE 1=1 ";

								while(list($key,$val) = each($paramsArray))
								{
									$str .= " AND $key = '$val' ";
								}

					$str .= $statement." ".$order;
		$str .= '';
		// echo $str; die();
		$this->query = $str;


		return $this->selectLimit($str,$limit,$from);
  }


  }
?>
